import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FFF",
  },
  wrapper: {
    backgroundColor: "#FFF",
    flex: 1,
    paddingTop: 20,
    paddingHorizontal: 20,
  },
  keyboardView: {
    flex: 1,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 40,
  },
  successContainer: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 60,
  },
  successIcon: {
    marginBottom: 20,
  },
  successTitle: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#4CAF50",
    marginBottom: 12,
    textAlign: "center",
  },
  successText: {
    fontSize: 16,
    color: "#666",
    textAlign: "center",
    lineHeight: 24,
    paddingHorizontal: 20,
  },
  formContainer: {
    marginTop: 20,
  },
  headerContainer: {
    alignItems: "center",
    marginBottom: 30,
  },
  iconContainer: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: "#F0F7FF",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 20,
  },
  title: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#3629B7",
    marginBottom: 8,
    textAlign: "center",
  },
  subtitle: {
    fontSize: 14,
    color: "#666",
    textAlign: "center",
    lineHeight: 20,
    paddingHorizontal: 20,
  },
  inputContainer: {
    marginBottom: 20,
  },
  inputLabel: {
    fontSize: 16,
    color: "#333",
    marginBottom: 12,
    textAlign: "center",
    fontWeight: "500",
  },
  codeInput: {
    backgroundColor: "#F8F9FA",
    borderWidth: 2,
    borderColor: "#E9ECEF",
    borderRadius: 12,
    padding: 20,
    fontSize: 28,
    fontWeight: "bold",
    color: "#333",
    letterSpacing: 8,
    textAlign: "center",
    marginBottom: 8,
  },
  backupCodeInput: {
    borderColor: "#4CAF50",
    backgroundColor: "#F0F9F0",
  },
  inputError: {
    borderColor: "#FF3B30",
  },
  errorText: {
    color: "#FF3B30",
    fontSize: 12,
    marginTop: 4,
    textAlign: "center",
  },
  attemptsText: {
    fontSize: 12,
    color: "#FF9800",
    textAlign: "center",
    marginTop: 8,
    fontWeight: "500",
  },
  timerContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 20,
    padding: 12,
    backgroundColor: "#FFF3E0",
    borderRadius: 10,
  },
  timerText: {
    fontSize: 14,
    color: "#FF9800",
    marginLeft: 8,
    fontWeight: "500",
  },
  resendButton: {
    flexDirection: "row",
    alignItems: "center",
  },
  resendText: {
    fontSize: 14,
    color: "#3629B7",
    marginLeft: 8,
    fontWeight: "500",
  },
  backupOption: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    padding: 12,
    marginBottom: 16,
  },
  backupOptionText: {
    fontSize: 14,
    color: "#666",
    marginLeft: 8,
  },
  backupOptionActive: {
    color: "#4CAF50",
    fontWeight: "500",
  },
  backupInfo: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#E3F2FD",
    padding: 12,
    borderRadius: 8,
    marginBottom: 20,
  },
  backupInfoText: {
    fontSize: 12,
    color: "#2196F3",
    marginLeft: 8,
    flex: 1,
    lineHeight: 18,
  },
  verifyButton: {
    backgroundColor: "#3629B7",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    padding: 16,
    borderRadius: 12,
    marginBottom: 16,
  },
  verifyButtonDisabled: {
    backgroundColor: "#A5D6A7",
    opacity: 0.7,
  },
  verifyButtonText: {
    color: "#FFF",
    fontSize: 16,
    fontWeight: "600",
    marginRight: 8,
  },
  backButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    padding: 12,
    marginBottom: 20,
  },
  backButtonText: {
    color: "#666",
    fontSize: 14,
    marginLeft: 6,
  },
  securityNote: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    padding: 12,
    backgroundColor: "#F0F9F0",
    borderRadius: 8,
  },
  securityNoteText: {
    fontSize: 12,
    color: "#2E7D32",
    marginLeft: 8,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.6)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContent: {
    width: "90%",
    maxWidth: 400,
  },
  modalContainer: {
    backgroundColor: "#FFF",
    borderRadius: 16,
    overflow: "hidden",
    padding: 15
  },
  modalHeader: {
    padding: 24,
    paddingBottom: 16,
    backgroundColor: "#F8F9FA",
    borderBottomWidth: 1,
    borderBottomColor: "#E9ECEF",
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#3629B7",
    marginBottom: 8,
    textAlign: "center",
  },
  modalSubtitle: {
    fontSize: 14,
    color: "#666",
    textAlign: "center",
    lineHeight: 20,
  },
  modalInput: {
    borderWidth: 2,
    borderColor: "#E9ECEF",
    borderRadius: 12,
    padding: 16,
    fontSize: 16,
    color: "#333",
    backgroundColor: "#F8F9FA",
    textAlign: "center",
    letterSpacing: 1,
  },
  modalInputError: {
    borderColor: "#FF3B30",
    backgroundColor: "#FFF5F5",
  },
  modalErrorText: {
    color: "#FF3B30",
    fontSize: 12,
    marginTop: 8,
    textAlign: "center",
  },
  modalHint: {
    color: "#666",
    fontSize: 12,
    marginTop: 8,
    textAlign: "center",
    fontStyle: "italic",
  },
  modalButtons: {
    flexDirection: "row",
    borderTopWidth: 1,
    borderTopColor: "#E9ECEF",
  },
  modalButton: {
    flex: 1,
    padding: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  cancelButton: {
    borderRightWidth: 1,
    borderRightColor: "#E9ECEF",
  },
  cancelButtonText: {
    color: "#666",
    fontSize: 16,
    fontWeight: "500",
  },
  submitButton: {
    backgroundColor: "#3629B7",
  },
  submitButtonDisabled: {
    backgroundColor: "#A5D6A7",
    opacity: 0.7,
  },
  submitButtonText: {
    color: "#FFF",
    fontSize: 16,
    fontWeight: "600",
  },
});
export default styles;
